swagger: '2.0'
info:
  version: 1.0.0
  title: Contact Form API
  description: API for handling contact form submissions
paths:
  /api/email:
    post:
      summary: Send an email
      description: Send an email using the data from the contact form
      parameters:
        - in: body
          name: body
          description: The email data
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              message:
                type: string
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Invalid request data
        '500':
          description: Server error
